version: "3.5"
volumes:
  node-ipc:
  node-db:
services:
  cardano-node:
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-1.35.5}
    environment:
      NETWORK: ${NETWORK:-preprod}
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  kuber:
    image: dquadrant/kuber:${KUBER_VERSION:-2.2.0}
    environment:
      NETWORK: ${NETWORK:-preprod}
    volumes:
      - node-ipc:/root/.cardano/preprod/
#      -node-ipc:/root/.cardano/mainnet/ for NETWORK=mainnet   or set CARDANO_NODE_SOCKET_PATH explicitly
#      -node-ipc:/root/.cardano/review/ for NETWORK=preview   or set CARDANO_NODE_SOCKET_PATH explicitly
    ports:
      - 8081:8081
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
