= https://github.com/Igodlab/plutus-pioneer-program/tree/main/Documentation[Unnoficial Plutus-Pioneer Documentation]
: email: igodlab@gmail.com
:author: Ignacio Calderon de la Barca
:toc: left
:reproducible:

The Plutus documentation presented in this repo is unnoficial. This is a brave effort to document with great detail all that has been thaught in the first ever cohort of developers for the Plutus language. The course was launched on April 5, 2021, thaught by Lars Brünjes through his https://www.youtube.com/channel/UCcAwSpbpQDDzEDRQqcDH8Iw[YouTube channel] alongside the *IO Global's Technical Community Discord*.

The motivation of this repo is anchored to the vision that if Cardano is set to become the decentraliced world-computer its documentation should be crystal clear and accessible to all audineces. This inspires the idea of constructing a **Layered Documentation** with each layer including deeper information. Ideally the depth of detail should lead to the theory from Academic papers. A good format or scheme to follow a priori is based on the **Zettelkasten** method.

== https://github.com/input-output-hk/plutus[Plutus]
The Architechture of the Plutus project comes from the Official IOHK Github. 

Table of Contents

== Plutus Core

Plutus Core is the language that actually goes on the blockchain. Consequently
this is the absolute core of the codebase, and everything depends on it.
It also includes the Plutus IR intermediary language.

include::plutus-core/LAYER1.adoc[]

== Plutus Tx

Plutus Tx is how we refer to the subset of Haskell which we compile into Plutus
Core. This is how users actually write Plutus contracts: they write Haskell
programs, part of which is compiled into Plutus Core. The rest of the program
can then use this compiled code when submitting transactions.

include::plutus-tx/LAYER1.adoc[]

include::plutus-tx-plugin/LAYER1.adoc[]

== Ledger

To write actual Plutus contracts we need a model of the ledger that we're
running on. There are two reasons for this:

- The on-chain code needs to work with the data: validators are given information
  about the current transaction being validated.
- The off-chain code needs to produce transactions to submit.
- We want to write tests that simulate the "full" behaviour of contracts, i.e.
  across time, in a multi-agent scenario.

include::plutus-ledger/LAYER1.adoc[]

== Contract modelling

We want to help people write "contracts". When we say that, we mean both:

. A high-level application that exposes a limited API and
is suitable for running inside something like a wallet smart contract backend.
. An implementation of a conceptual "contract" (e.g. a crowdfunding contract),
including both the on-chain code and the eventual contract application.

These packages are geared towards providing the tools to do that, and building
up examples to ensure that we have adequate functionality.

include::plutus-contract/LAYER1.adoc[]

include::plutus-use-cases/LAYER1.adoc[]


 


